if (project.ext.has('sfmJavaCompilerConfigured')) {
    throw new GradleException("java-compiler.gradle must not be applied more than once")
}

if (!project.ext.has('sfmPluginsConfigured')) {
    throw new GradleException("java-compiler.gradle requires versioned-plugins.gradle to be applied first")
}

ext.sfmJavaCompilerConfigured = true

afterEvaluate {
    tasks.withType(JavaCompile).tap {
        configureEach {
            options.compilerArgs << "-Xmaxerrs" << "0"
        }
    }
}
