if (project.ext.has('sfmTestConfigured')) {
    throw new GradleException("test.gradle must not be applied more than once")
}

if (!project.ext.has('sfmPluginsConfigured')) {
    throw new GradleException("test.gradle requires versioned-plugins.gradle to be applied first")
}

ext.sfmTestConfigured = true

test {
    useJUnitPlatform()
}
