package ca.teamdman.sfm.client.screen.review.comment;
import org.junit.jupiter.api.Test;
import java.util.List;
import static org.junit.jupiter.api.Assertions.*;
class SFMReviewCommentUiTests {
 @Test void hashtagsMatchFrozenQuotedEscapedUnicodeAndBoundarySemantics(){assertEquals(java.util.Set.of("#approved","#\"needs review\"","#café"),SFMCommentHashtags.derive("#Approved #\"Needs Review\" #CAFÉ #cafe\u0301 ignored#suffix"));assertEquals(java.util.Set.of("#\"escaped \"quote\"\""),SFMCommentHashtags.derive("#\"escaped \\\"quote\\\"\""));assertEquals(java.util.Set.of("#\"path\\name\""),SFMCommentHashtags.derive("#\"path\\\\name\""));assertTrue(SFMCommentHashtags.derive("word#embedded #\"unterminated").isEmpty());assertTrue(SFMCommentHashtags.derive("#\"\" #\"   \"").isEmpty());}
 @Test void literalCreateEditAndArchiveUseTheSameProductionPanelPathAsUserInput(){var panel=new SFMReviewCommentPanel(new SFMFixtureReviewCommentDataSource());panel.selectLiteral(new SFMReviewCommentDataSource.RangeView(SFMFixtureReviewCommentDataSource.AFTER,20,30));panel.beginCreate();panel.replaceDraftText("#question initial");panel.submitText();var created=panel.session().comments().stream().filter(c->c.text().equals("#question initial")).findFirst().orElseThrow();assertEquals(java.util.Set.of("#question"),SFMCommentHashtags.derive(created.text()));panel.beginEdit();panel.replaceDraftText("#approved checked");panel.submitText();assertEquals(java.util.Set.of("#approved"),SFMCommentHashtags.derive(panel.session().comments().stream().filter(c->c.id().equals(created.id())).findFirst().orElseThrow().text()));panel.archiveActive();assertTrue(panel.session().comments().stream().filter(c->c.id().equals(created.id())).findFirst().orElseThrow().archived());}
 @Test void fixtureKeepsBeforeAfterOverlapMigrationAndLegacyProjection(){var v=new SFMFixtureReviewCommentDataSource().refresh();assertEquals(List.of(SFMReviewCommentDataSource.Side.BEFORE,SFMReviewCommentDataSource.Side.AFTER),v.documents().stream().map(SFMReviewCommentDataSource.DocumentView::side).toList());assertTrue(v.comments().stream().filter(c->c.ranges().stream().anyMatch(r->r.startByte()<68&&r.endByte()>60)).count()>=2);assertEquals(List.of(SFMReviewCommentDataSource.EvaluationStatus.RESOLVED_EXACTLY,SFMReviewCommentDataSource.EvaluationStatus.CONTENT_CHANGED,SFMReviewCommentDataSource.EvaluationStatus.INVALID_RULE),v.migrations().stream().map(SFMReviewCommentDataSource.MigrationView::status).toList());assertFalse(v.legacyRows().isEmpty());}
 @Test void overlapCommentsAreIndependentlySelectableThroughUserKeyPath(){var panel=new SFMReviewCommentPanel(new SFMFixtureReviewCommentDataSource());panel.applyAutomation("overlap");String first=panel.session().comments().get(1).id();assertTrue(panel.keyPressed(org.lwjgl.glfw.GLFW.GLFW_KEY_UP,0,0));assertFalse(panel.narration().getString().contains(first));assertTrue(panel.keyPressed(org.lwjgl.glfw.GLFW.GLFW_KEY_DOWN,0,0));assertTrue(panel.narration().getString().contains(first));}
 @Test void visibleBackgroundStyleEditingIsTypedAndDoesNotMutateCommentSemantics(){var s=new SFMFixtureReviewCommentDataSource();var comments=s.refresh().comments();s.updateStyleColour("problem-underline",SFMReviewCommentDataSource.StyleChannel.BACKGROUND,0xFFAA11CC);assertEquals(0xFFAA11CC,s.refresh().styleRules().stream().filter(r->r.id().equals("problem-underline")).findFirst().orElseThrow().background());assertEquals(comments,s.refresh().comments());}
}
